# Generated by Django 5.0.2 on 2024-04-04 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.ForeignKey(default=324, on_delete=django.db.models.deletion.CASCADE, related_name='review_usernames', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
