# Generated by Django 5.0.2 on 2024-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.TextField(),
        ),
    ]
