# Generated by Django 5.0.2 on 2024-03-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=None, max_length=150, null=True, unique=True),
        ),
    ]
