# Generated by Django 5.0.2 on 2024-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
