# Generated by Django 5.0.2 on 2024-03-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_orderitem_created_at_orderitem_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
