# Generated by Django 5.0.2 on 2024-03-19 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True)),
                ('characteristics', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Air purifying', 'Air purifying'), ('Pet friendly', 'Pet friendly'), ('Hanging plant', 'Hanging plant')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, choices=[('Sun', 'Sun'), ('Partial sun', 'Partial sun'), ('(Half) shade', '(Half) shade')], max_length=50, null=True)),
                ('plant_family', models.CharField(blank=True, choices=[('Ferns', 'Ferns'), ('Succulents', 'Succulents'), ('Palms', 'Palms'), ('Cacti', 'Cacti')], max_length=50, null=True)),
                ('water_care', models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly'), ('Monthly', 'Monthly')], max_length=20, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
